# # Do not modify this file!  It was generated by ‘nixos-generate-config’
# # and may be overwritten by future invocations.  Please make changes
# # to /etc/nixos/configuration.nix instead.
# { config, lib, pkgs, modulesPath, ... }:

# {
#   imports =
#     [ (modulesPath + "/installer/scan/not-detected.nix")
#     ];

#   boot.initrd.availableKernelModules = [ "ehci_pci" "ahci" "ums_realtek" "usb_storage" "sd_mod" "sr_mod" ];
#   boot.initrd.kernelModules = [ ];
#   boot.kernelModules = [ "kvm-intel" ];
#   boot.extraModulePackages = [ ];

#   fileSystems."/" =
#     { device = "/dev/disk/by-uuid/1acae91f-ffb3-40e6-8e0d-dd2b63c6c4bb";
#       fsType = "ext4";
#     };

#   swapDevices = [ ];

#   nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
#   hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
# }

# ⚠️ Arquivo gerado automaticamente pelo NixOS
# Ajustes manuais devem ir em configuration.nix ou hosts/<host>/default.nix

{ config, lib, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  ############################################
  # Initrd / Kernel
  ############################################
  boot.initrd.availableKernelModules = [
    "xhci_pci"   # USB moderno
    "ahci"       # SATA
    "nvme"       # NVMe (se existir, não atrapalha)
    "usb_storage"
    "sd_mod"
  ];

  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  ############################################
  # Filesystems
  ############################################
  fileSystems."/" = {
    device = "/dev/disk/by-uuid/1acae91f-ffb3-40e6-8e0d-dd2b63c6c4bb";
    fsType = "ext4";
  };

  swapDevices = [ ];

  ############################################
  # Platform
  ############################################
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";

  ############################################
  # CPU Microcode
  ############################################
  hardware.cpu.intel.updateMicrocode =
    lib.mkDefault config.hardware.enableRedistributableFirmware;
}
