# modules/desktops/niri/config.nix
# Main Niri config.kdl file - imports all modular configurations
{ config, lib, hostname, ... }:

let
  isMacbook = hostname == "macbook-nixos" || hostname == "macbook";
  
  mainConfigKdl = ''
    // ============================================
    // NIRI MAIN CONFIGURATION
    // ============================================
    // This configuration is modularized and split into multiple files.
    // Each file is generated by a corresponding .nix module.
    //
    // Structure:
    //   - config.d/input.kdl        → Input devices (keyboard, mouse, touchpad)
    //   - config.d/output.kdl       → Monitor configuration
    //   - config.d/layout.kdl       → Layout, gaps, borders, focus-ring
    //   - config.d/keybindings.kdl  → All keyboard shortcuts
    //   - config.d/window-rules.kdl → Per-application window rules
    //   - config.d/animations.kdl   → Animation settings
    //   - dms/cursor.kdl            → DMS cursor configuration
    //
    // Companion apps (Waybar, Mako, Fuzzel) are configured separately
    // in their respective nix modules.
    // ============================================

    include "config.d/input.kdl"
    include "config.d/output.kdl"
    include "config.d/layout.kdl"
    include "config.d/keybindings.kdl"
    include "config.d/window-rules.kdl"
    include "config.d/animations.kdl"
    include "dms/cursor.kdl"
  '';
in
lib.mkIf isMacbook {
  xdg.configFile."niri/config.kdl".text = mainConfigKdl;
}
