# modules/nixos/ssh.nix
#
# openssh (server) + programs.ssh (client config). Extraído 1:1 de
# configuration.nix (split cirúrgico, sem mudança de comportamento).
{common, ...}: let
  inherit (common) username;
  sshKeysDir = "/home/${username}/.ssh";
in {
  # ==================== SSH ====================
  services.openssh = {
    enable = true;

    hostKeys = [
      {
        path = "/etc/ssh/ssh_host_ed25519_key";
        type = "ed25519";
      }
    ];
  };

  # SSH client configuration is generated by NixOS.
  # No manual /etc/ssh/ssh_config.d/50-borba.conf is needed.
  programs.ssh = {
    extraConfig = ''
      Host 192.168.* *.infra
        HostName %h
        User ${username}
        IdentityFile ${sshKeysDir}/id_ed25519_infra
        IdentitiesOnly yes

      Host github.com gitlab.com
        User git
        IdentityFile ${sshKeysDir}/id_ed25519_github
        IdentitiesOnly yes

      Host gitea.com
        User git
        IdentityFile ${sshKeysDir}/id_ed25519_github
        IdentitiesOnly yes

      Host codeberg.org
        User git
        IdentityFile ${sshKeysDir}/id_ed25519_github
        IdentitiesOnly yes

      Host codefloe.com
        User git
        IdentityFile ${sshKeysDir}/id_ed25519_github
        IdentitiesOnly yes

      Host forgejo.local
        HostName forgejo.local
        User git
        IdentityFile ${sshKeysDir}/id_ed25519_github
        IdentitiesOnly yes
    '';
  };
}
